### ISSUE TITLE
How can the training results be visualized？

### ISSUE THREAD

**Issue by Valkyrie1215** [lfranke/TRIPS#25]
Thank you very much for open-sourcing such an impressive work. After training, there are many .pth files in my experiments directory. How can I visualize the results of the training, similar to the .ply files that can be viewed by 3dgs?
![image](https://github.com/lfranke/TRIPS/assets/104125743/deefc6ec-6278-42d5-bc9c-07ab1d3f80bf)

**Comment by lfranke** [comment]
Hi,
you can visualize it with the `viewer` with  `--scene_dir` setting the scene trained (in this case `tt_playground`).

**Comment by arlo-ml** [comment]
Hi,
is there any plan to support a .ply export, so that we can check point-based radiance field rendering using other apps like Unity?
With Nerfstudio, for example, we can export splatfacto trainings using the ns-export gaussian-splat command, and we have a .ply that can be easily adapted to the original inria format (see screenshot below)

![scale_01](https://github.com/lfranke/TRIPS/assets/63562596/ce278764-9d27-42d2-a14e-c04730dcf3b6)

**Comment by lfranke** [comment]
Hi, this is currently a bit difficult, as our point colors/descriptors have no real RGB meaning without the neural network convolutions afterwards.

**Comment by hariharan1412** [comment]
Hello @lfranke I'm really amazed by your work and wants thank you,

And I have a doubt,

> Hi, this is currently a bit difficult, as our point colors/descriptors have no real RGB meaning without the neural network convolutions afterwards.

Since you have mentioned it has "no real RGB" value, is it possible to export a .PLY file with only Pointclould Structures not colors?
